version: "3"
services:
  cms:
    build: .
    image: ecopark_cms:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 200M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "8084:80"
    networks:
      - cmsnet
    volumes:
      - "/home/apps/ecopark/data/cms:/var/www/html/assets/images"
networks:
  cmsnet: